<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SiteConfig', 'doctrine');

/**
 * BaseSiteConfig
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $ConfigKey
 * @property string $ConfigValue
 * 
 * @method string     getConfigKey()   Returns the current record's "ConfigKey" value
 * @method string     getConfigValue() Returns the current record's "ConfigValue" value
 * @method SiteConfig setConfigKey()   Sets the current record's "ConfigKey" value
 * @method SiteConfig setConfigValue() Sets the current record's "ConfigValue" value
 * 
 * @package    counceledge
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSiteConfig extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('SiteConfig');
        $this->hasColumn('ConfigKey', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('ConfigValue', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'created' => 
             array(
              'name' => 'CreateDateTime',
              'type' => 'timestamp',
             ),
             'updated' => 
             array(
              'name' => 'UpdateDateTime',
              'type' => 'timestamp',
             ),
             ));
        $this->actAs($timestampable0);
    }
}