<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AttorneyContact', 'doctrine');

/**
 * BaseAttorneyContact
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $Id
 * @property integer $UserId
 * @property string $Label
 * @property string $FieldType
 * @property string $Options
 * @property enum $Required
 * @property integer $Ordering
 * @property string $OptionsSlug
 * @property Doctrine_Collection $AttorneyContactUsers
 * 
 * @method integer             getId()                   Returns the current record's "Id" value
 * @method integer             getUserId()               Returns the current record's "UserId" value
 * @method string              getLabel()                Returns the current record's "Label" value
 * @method string              getFieldType()            Returns the current record's "FieldType" value
 * @method string              getOptions()              Returns the current record's "Options" value
 * @method enum                getRequired()             Returns the current record's "Required" value
 * @method integer             getOrdering()             Returns the current record's "Ordering" value
 * @method string              getOptionsSlug()          Returns the current record's "OptionsSlug" value
 * @method Doctrine_Collection getAttorneyContactUsers() Returns the current record's "AttorneyContactUsers" collection
 * @method AttorneyContact     setId()                   Sets the current record's "Id" value
 * @method AttorneyContact     setUserId()               Sets the current record's "UserId" value
 * @method AttorneyContact     setLabel()                Sets the current record's "Label" value
 * @method AttorneyContact     setFieldType()            Sets the current record's "FieldType" value
 * @method AttorneyContact     setOptions()              Sets the current record's "Options" value
 * @method AttorneyContact     setRequired()             Sets the current record's "Required" value
 * @method AttorneyContact     setOrdering()             Sets the current record's "Ordering" value
 * @method AttorneyContact     setOptionsSlug()          Sets the current record's "OptionsSlug" value
 * @method AttorneyContact     setAttorneyContactUsers() Sets the current record's "AttorneyContactUsers" collection
 * 
 * @package    counceledge
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAttorneyContact extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('AttorneyContact');
        $this->hasColumn('Id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('UserId', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('Label', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('FieldType', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('Options', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('Required', 'enum', 3, array(
             'type' => 'enum',
             'fixed' => 0,
             'unsigned' => false,
             'values' => 
             array(
              0 => 'Yes',
              1 => 'No',
             ),
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 3,
             ));
        $this->hasColumn('Ordering', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('OptionsSlug', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Users as AttorneyContactUsers', array(
             'local' => 'UserId',
             'foreign' => 'Id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'created' => 
             array(
              'name' => 'CreateDateTime',
              'type' => 'timestamp',
             ),
             'updated' => 
             array(
              'name' => 'UpdateDateTime',
              'type' => 'timestamp',
             ),
             ));
        $this->actAs($timestampable0);
    }
}