<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ThemeOptions', 'doctrine');

/**
 * BaseThemeOptions
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $Id
 * @property integer $ThemeId
 * @property integer $WebsiteId
 * @property string $OptionKey
 * @property string $OptionValue
 * @property Theme $ThemeOptionsTheme
 * 
 * @method integer      getId()                Returns the current record's "Id" value
 * @method integer      getThemeId()           Returns the current record's "ThemeId" value
 * @method integer      getWebsiteId()         Returns the current record's "WebsiteId" value
 * @method string       getOptionKey()         Returns the current record's "OptionKey" value
 * @method string       getOptionValue()       Returns the current record's "OptionValue" value
 * @method Theme        getThemeOptionsTheme() Returns the current record's "ThemeOptionsTheme" value
 * @method ThemeOptions setId()                Sets the current record's "Id" value
 * @method ThemeOptions setThemeId()           Sets the current record's "ThemeId" value
 * @method ThemeOptions setWebsiteId()         Sets the current record's "WebsiteId" value
 * @method ThemeOptions setOptionKey()         Sets the current record's "OptionKey" value
 * @method ThemeOptions setOptionValue()       Sets the current record's "OptionValue" value
 * @method ThemeOptions setThemeOptionsTheme() Sets the current record's "ThemeOptionsTheme" value
 * 
 * @package    counceledge
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseThemeOptions extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ThemeOptions');
        $this->hasColumn('Id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('ThemeId', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('WebsiteId', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('OptionKey', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 150,
             ));
        $this->hasColumn('OptionValue', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Theme as ThemeOptionsTheme', array(
             'local' => 'ThemeId',
             'foreign' => 'Id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'created' => 
             array(
              'name' => 'CreateDateTime',
              'type' => 'timestamp',
             ),
             'updated' => 
             array(
              'name' => 'UpdateDateTime',
              'type' => 'timestamp',
             ),
             ));
        $this->actAs($timestampable0);
    }
}