<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Statistics', 'doctrine');

/**
 * BaseStatistics
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $Id
 * @property integer $WebsiteId
 * @property string $IpAddress
 * @property date $VisitDate
 * @property UsersWebsite $StatisticsUsersWebsite
 * 
 * @method integer      getId()                     Returns the current record's "Id" value
 * @method integer      getWebsiteId()              Returns the current record's "WebsiteId" value
 * @method string       getIpAddress()              Returns the current record's "IpAddress" value
 * @method date         getVisitDate()              Returns the current record's "VisitDate" value
 * @method UsersWebsite getStatisticsUsersWebsite() Returns the current record's "StatisticsUsersWebsite" value
 * @method Statistics   setId()                     Sets the current record's "Id" value
 * @method Statistics   setWebsiteId()              Sets the current record's "WebsiteId" value
 * @method Statistics   setIpAddress()              Sets the current record's "IpAddress" value
 * @method Statistics   setVisitDate()              Sets the current record's "VisitDate" value
 * @method Statistics   setStatisticsUsersWebsite() Sets the current record's "StatisticsUsersWebsite" value
 * 
 * @package    counceledge
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStatistics extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('Statistics');
        $this->hasColumn('Id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('WebsiteId', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('IpAddress', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 150,
             ));
        $this->hasColumn('VisitDate', 'date', null, array(
             'type' => 'date',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('UsersWebsite as StatisticsUsersWebsite', array(
             'local' => 'WebsiteId',
             'foreign' => 'Id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'created' => 
             array(
              'name' => 'CreateDateTime',
              'type' => 'timestamp',
             ),
             'updated' => 
             array(
              'name' => 'UpdateDateTime',
              'type' => 'timestamp',
             ),
             ));
        $this->actAs($timestampable0);
    }
}