<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CaseDocuments', 'doctrine');

/**
 * BaseCaseDocuments
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $Id
 * @property integer $CaseId
 * @property string $BillDocumentRealName
 * @property string $BillDocumentSystemName
 * @property Cases $CaseDocumentsCases
 * 
 * @method integer       getId()                     Returns the current record's "Id" value
 * @method integer       getCaseId()                 Returns the current record's "CaseId" value
 * @method string        getBillDocumentRealName()   Returns the current record's "BillDocumentRealName" value
 * @method string        getBillDocumentSystemName() Returns the current record's "BillDocumentSystemName" value
 * @method Cases         getCaseDocumentsCases()     Returns the current record's "CaseDocumentsCases" value
 * @method CaseDocuments setId()                     Sets the current record's "Id" value
 * @method CaseDocuments setCaseId()                 Sets the current record's "CaseId" value
 * @method CaseDocuments setBillDocumentRealName()   Sets the current record's "BillDocumentRealName" value
 * @method CaseDocuments setBillDocumentSystemName() Sets the current record's "BillDocumentSystemName" value
 * @method CaseDocuments setCaseDocumentsCases()     Sets the current record's "CaseDocumentsCases" value
 * 
 * @package    counceledge
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCaseDocuments extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('CaseDocuments');
        $this->hasColumn('Id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('CaseId', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('BillDocumentRealName', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 150,
             ));
        $this->hasColumn('BillDocumentSystemName', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 150,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Cases as CaseDocumentsCases', array(
             'local' => 'CaseId',
             'foreign' => 'Id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'created' => 
             array(
              'name' => 'CreateDateTime',
              'type' => 'timestamp',
             ),
             'updated' => 
             array(
              'name' => 'UpdateDateTime',
              'type' => 'timestamp',
             ),
             ));
        $this->actAs($timestampable0);
    }
}