<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CaseActivities', 'doctrine');

/**
 * BaseCaseActivities
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $Id
 * @property integer $CaseId
 * @property enum $ActivityType
 * @property string $Description
 * @property Cases $CaseActivitiesCases
 * 
 * @method integer        getId()                  Returns the current record's "Id" value
 * @method integer        getCaseId()              Returns the current record's "CaseId" value
 * @method enum           getActivityType()        Returns the current record's "ActivityType" value
 * @method string         getDescription()         Returns the current record's "Description" value
 * @method Cases          getCaseActivitiesCases() Returns the current record's "CaseActivitiesCases" value
 * @method CaseActivities setId()                  Sets the current record's "Id" value
 * @method CaseActivities setCaseId()              Sets the current record's "CaseId" value
 * @method CaseActivities setActivityType()        Sets the current record's "ActivityType" value
 * @method CaseActivities setDescription()         Sets the current record's "Description" value
 * @method CaseActivities setCaseActivitiesCases() Sets the current record's "CaseActivitiesCases" value
 * 
 * @package    counceledge
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCaseActivities extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('CaseActivities');
        $this->hasColumn('Id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('CaseId', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('ActivityType', 'enum', 22, array(
             'type' => 'enum',
             'fixed' => 0,
             'unsigned' => false,
             'values' => 
             array(
              0 => 'CustomerBillsSubmitted',
              1 => '3rdPartyBillsSubmitted',
              2 => '3rdPartyBillsRejected',
              3 => 'CheckSent',
              4 => 'PaymentReceived',
             ),
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 22,
             ));
        $this->hasColumn('Description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Cases as CaseActivitiesCases', array(
             'local' => 'CaseId',
             'foreign' => 'Id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'created' => 
             array(
              'name' => 'CreateDateTime',
              'type' => 'timestamp',
             ),
             'updated' => 
             array(
              'name' => 'UpdateDateTime',
              'type' => 'timestamp',
             ),
             ));
        $this->actAs($timestampable0);
    }
}