<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Testimonial', 'doctrine');

/**
 * BaseTestimonial
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $Id
 * @property string $ClientName
 * @property string $CompanyName
 * @property string $Description
 * 
 * @method integer     getId()          Returns the current record's "Id" value
 * @method string      getClientName()  Returns the current record's "ClientName" value
 * @method string      getCompanyName() Returns the current record's "CompanyName" value
 * @method string      getDescription() Returns the current record's "Description" value
 * @method Testimonial setId()          Sets the current record's "Id" value
 * @method Testimonial setClientName()  Sets the current record's "ClientName" value
 * @method Testimonial setCompanyName() Sets the current record's "CompanyName" value
 * @method Testimonial setDescription() Sets the current record's "Description" value
 * 
 * @package    counceledge
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTestimonial extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('Testimonial');
        $this->hasColumn('Id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('ClientName', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 150,
             ));
        $this->hasColumn('CompanyName', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 150,
             ));
        $this->hasColumn('Description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'created' => 
             array(
              'name' => 'CreateDateTime',
              'type' => 'timestamp',
             ),
             'updated' => 
             array(
              'name' => 'UpdateDateTime',
              'type' => 'timestamp',
             ),
             ));
        $this->actAs($timestampable0);
    }
}