all:
    stylesheets:    [legalgrip/jquery.mCustomScrollbar.css, legalgrip/jquery.fancybox.css, legalgrip/star_rating.css]
    javascripts:    [legalgrip/jquery-ui-1.8.21.custom.min.js, legalgrip/jquery.mousewheel.min.js, legalgrip/jquery.mCustomScrollbar.js, legalgrip/jquery.fancybox.js]
