<?php
// auto-generated by sfViewConfigHandler
// date: 2014/01/02 13:35:15
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'Counsel Edge', false, false);

  $response->addStylesheet('frontend/normalize.css', '', array ());
  $response->addStylesheet('frontend/style.css', '', array ());
  $response->addStylesheet('frontend/sequencejs-theme.modern-slide-in.css', '', array ());
  $response->addStylesheet('frontend/sequencejs-theme.modern-slide-in.ie.css', '', array (  'condition' => 'lt IE 8',));
  $response->addJavascript('frontend/modernizr-2.0.6.min.js', '', array ());
  $response->addJavascript('frontend/jquery.js', '', array ());
  $response->addJavascript('frontend/sequence.jquery.js', '', array ());
  $response->addJavascript('frontend/sequence.jquery-min.js', '', array ());
  $response->addJavascript('frontend/slides.min.jquery.js', '', array ());


