<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/12/16 19:27:44

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=counceledge',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
