<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/12/17 10:12:07
sfConfig::add(array(
  'mod_paymenthistory_enabled' => true,
  'mod_paymenthistory_view_class' => 'sfPHP',
));
