<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/12/17 10:05:42
sfConfig::add(array(
  'mod_dashboardreport_enabled' => true,
  'mod_dashboardreport_view_class' => 'sfPHP',
));
