<?php
// auto-generated by sfSecurityConfigHandler
// date: 2013/12/17 09:59:36
$this->security = array (
  'verifyaccount' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'admin',
        1 => 'staff',
        2 => 'customer',
      ),
    ),
  ),
);
