<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/12/17 09:59:36
sfConfig::add(array(
  'mod_administrators_enabled' => true,
  'mod_administrators_view_class' => 'sfPHP',
));
