<?php
// auto-generated by sfSecurityConfigHandler
// date: 2013/12/16 19:27:44
$this->security = array (
  'all' => 
  array (
    'is_secure' => false,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'admin',
        1 => 'staff',
        2 => 'customer',
      ),
    ),
  ),
);
