<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2014/01/23 17:05:01
sfConfig::add(array(
  'mod_paymentreceived_enabled' => true,
  'mod_paymentreceived_view_class' => 'sfPHP',
));
