<?php
// auto-generated by sfSecurityConfigHandler
// date: 2014/01/23 17:05:01
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'admin',
        1 => 'staff',
        2 => 'customer',
      ),
    ),
  ),
);
