<?php

/**
 * AttorneyContactTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AttorneyContactTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AttorneyContactTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AttorneyContact');
    }

    /**
     * This function returns all the Customers Users .
     *
     * @return unknown
     */
    public static function getCustomers($userId)
    {
        $queryUser = Doctrine_Query::create()
        ->select('*')
        ->from('AttorneyContact')
        ->where('UserId = ? ', $userId)
        ->OrderBy('Ordering');

        $result = $queryUser->fetchArray();
        return $result;
    }

    public static function getCustomersField($userId, $field)
    {
        $queryUser = Doctrine_Query::create()
        ->select('*')
        ->from('AttorneyContact')
        ->where('UserId = ? ', $userId)
        ->where('FieldType = ? ', $field);

        $result = $queryUser->fetchArray();
        return $result;
    }

    /* this function is for counceledge Listing */
    public function customerListing($userId)
    {
        if(!is_numeric($userId))
        return false;

        $queryUser = Doctrine_Query::create()
        ->select('*')
        ->from('AttorneyContact')
        ->where('UserId = ? ', $userId)
        ->OrderBy('Ordering');

        return $queryUser;
    }

    /* this function is made for updating the order of Customer*/
    public function updateOrdering($snId,$snOrder)
    {
        if(!is_numeric($snId) || !is_numeric($snOrder))
        return false;

        Doctrine_Query::create()
        ->update('AttorneyContact')
        ->set('Ordering', '?', $snOrder)
        ->where('Id = ?', $snId)
        ->execute();
    }

    public function updateUserElementOrdrAtDelete($orderNumber,$userId)
    {
        if(!is_numeric($orderNumber))
        return false;

        $sql = Doctrine_Query::create()
        ->update('AttorneyContact f')
        ->set('f.Ordering',  ('f.Ordering -1 '))
        ->where('f.Ordering > ?',$orderNumber)
        ->andWhere('f.UserId = ?',$userId)
        ->execute();

        return true;
    }

    /**
     * This function will retunr Max Odering of Contact Page Input Types 
     *
     * @param unknown_type $UserId
     * @return unknown
     */
    public static function contactMaxOrder($UserId)
    {
        if(!is_numeric($UserId))
        return false;

        $maxOrder =	Doctrine_Query::create()
        ->select("MAX(cc.Ordering) as max")
        ->from('AttorneyContact cc')
        ->where('cc.UserId = ?', $UserId)
        ->fetchArray();

        if(empty($maxOrder[0]["max"]) &&  $maxOrder[0]["max"] == '') {
            return 0;
        }else {
            return ( ($maxOrder[0]["max"] + 1) );
        }
    } // End of Function

}