<?php

/**
 * CaseActivitiesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CaseActivitiesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CaseActivitiesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CaseActivities');
    }
}