<?php

/**
 * CaseActivities
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    counceledge
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class CaseActivities extends BaseCaseActivities
{

    public function saveActivity($activityArr = array()){

        #$caseActivity = new CaseActivities();
        $this->setCaseId($activityArr['CaseId']);
        $this->setActivityType($activityArr['ActivityType']);
        $this->setDescription($activityArr['Description']);
        $this->save();

    }



}