<?php

/**
 * CMSPages
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    counceledge
 * @subpackage model
 * @author     Krunal Nerikar
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class CMSPages extends BaseCMSPages
{
	public function __toString()
	{
		  return $this->getTitle();
	}
	
	public function deletePersonalCmsPage($id, $websiteId)
	{
		if(!is_numeric($id) || !is_numeric($websiteId))
			return false;

        Doctrine_Query::create()
        ->delete('CMSPages C')
        ->where('C.Id = ?', $id)
        ->andWhere('C.WebsiteId = ?', $websiteId)
        ->execute();
        return true;
	}
	
	/**
     * This function is for delete website data
     *
     * @param  integer $websiteId
     * @auther jaydip dodiya
     * @return boolean
     */
	public function deleteCMSPagesWebsiteData($websiteId)
	{
		if(!is_numeric($websiteId))
			return false;

		Doctrine_Query::create()
		->delete('CMSPages C')
		->where('C.WebsiteId  = ?', $websiteId)
		->execute();

		return true;
	}
}