<?php

/**
 * CMSPagesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CMSPagesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CMSPagesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CMSPages');
    }

    /**
     * This Function is use for check the unique key is unique or not
     *
     * @param unknown_type $id
     * @param unknown_type $newUniqueKey
     * @return flage variable i.e. true or flase
     */
    public static function uniqueKeyCheck($id,$newUniqueKey)
    {
        $dbUniqueKey = Doctrine_Query::create()
        ->select('c.UniqueKey')
        ->from('CMSPages c')
        ->where('c.id != ?',$id)
        ->andWhere('c.UniqueKey = ?',$newUniqueKey);
        $resultUniqueKey = $dbUniqueKey->fetchArray();
        $dbUniqueKey->free();
        if (count($resultUniqueKey) == 1) {
            return true;
        }else {
            return false;
        }
    }

    public static function getCmsPageForView($uniqueKey)
    {
        $sql = Doctrine_Query::create()
        ->from('CMSPages cms')
        ->where('cms.WebsiteId = ?',1)
        ->andWhere('cms.UniqueKey = ?','1_'.$uniqueKey);
        $arrAbout = $sql->fetchOne();
        return $arrAbout;
    }

    /**
	* This function will return the Static page value from Database.
	* @param string $key
	* @return mixed(object)
	*/
    public static function getStaticPage($pageName, $webId){
        if(!$pageName)
        return false;
        $qStaticPage = Doctrine_Query::create()
        ->from('CMSPages cms')
        ->where("cms.slug = ?",$pageName)
        ->andWhere("cms.WebsiteId = ?", $webId);
        //clsCommon::pr($qStaticPage->fetchArray(),1);
        return $qStaticPage->fetchOne();
    }

    /**
	 * THIS FUNCTION IS USE FOR EXISTING SLUG VALUE
	 *
	 * @param unknown_type $websiteId
	 * @param unknown_type $title
	 * @return OBJECT
	 */
    public static function checkSlugExist($websiteId,$title, $act, $id = NULL)
    {
        $sql = Doctrine_Query::create()
        ->from('CMSPages cms')
        ->where('cms.WebsiteId = ?',$websiteId)
        ->andWhere('cms.Slug = ?',$title);
        //echo $title;
        //echo $sql->getSqlQuery();die;
        if($act == 'edit' && !empty($id ))
        $sql->andWhere('cms.Id != ?', $id);

        return $sql->fetchArray();
    }

    public static function getHomePageData($websiteId){
        $sql = Doctrine_Query::create()
        ->from('CMSPages cms')
        ->where('cms.WebsiteId = ?',$websiteId)
        ->andWhere('cms.Slug = ?','home');
        $returnHome = $sql->fetchOne();
        $sql->free();
        return $returnHome;
    }

    /** Function to Get CMS PAge Id based on Slug For Theme Default content Setup
     * 
     * 
     * @param unknown_type $websitId
     * @param unknown_type $SlugTitle
     * @return unknown
     */
    public static function getCMSPageBasedonSlug($websitId, $SlugTitle){
        $sql = Doctrine_Query::create()
        ->from('CMSPages cms')
        ->where('cms.WebsiteId = ?', $websitId)
        ->andWhere('cms.Slug = ?', $SlugTitle);
        $result = $sql->fetchArray();
        #clsCommon::pr($returnHome, 1);
        $sql->free();
        return $result[0]['Id'];

    } // End of Function
}