<?php

/**
 * Counties
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    counceledge
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Counties extends BaseCounties
{
     public function __toString(){
        return $this->getName();
    }

    public static function getCountyByStateId($state_id){
		$q = Doctrine_Query::create()
			->select('c.Id, c.Name ')
			->from('Counties c')
			->where('c.StateId = ?', $state_id)
			->orderBy('c.Name ASC');
		return $q->execute();
	}
}
