<?php

/**
 * CountiesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CountiesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CountiesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Counties');
    }

    public static function checkStatesCounties($stateId)
    {
        if(!is_numeric($stateId))
        return false;

        $countiesData = Doctrine_Query::create()
        ->select("C.*")
        ->from('Counties C')
        ->where('C.StateId = ?', $stateId)
        ->fetchArray();

        if(count($countiesData)>0)
        return true;
        else
        return false;
    }

    /**
     * Function to check counties name exist or not
     *
     * @param integer $stateId
     * @param string $ssName
     */
    public static function checkUniqueCountiesName($ssName, $stateId)
    {
        if(!is_numeric($stateId) || !is_string($ssName))
        return false;

        $asResult = Doctrine_Query::create()
        ->select("C.*")
        ->from('Counties C')
        ->where("C.Name = ?", $ssName)
        ->andWhere("C.StateId = ?", $stateId)
        ->fetchArray();

        return $asResult;
    }

    /**
     * Function to get all counties of perticular state
     *
     * @param integer $stateId
     */
    public static function getCountiesName($stateId)
    {
        if(!is_numeric($stateId))
        return false;

        $asResult = Doctrine_Query::create()
        ->select("C.*")
        ->from('Counties C')
        ->where("C.StateId = ?", $stateId)
        ->fetchArray();

        return $asResult;
    }

    /**
	 * Function to Get Key Value Pair of County => State
	 *
	 */
    public static function getCountyState() {
        $sql = Doctrine_Query::create()
        ->select("c.*")
        ->from('Counties c')
        ->where(" c.Status = ?", "Active")
        ->fetchArray();

        $stateArr = array();
        if(!empty($sql)){
            for($i= 0; $i < count($sql) ; $i++ ) {
                $stateArr[$sql[$i]['Id']] = $sql[$i]['StateId'];
            } // End of Function

        }
        #clsCommon::pr($stateArr);
        return $stateArr;
    } // End of Function

    /**
     * Function to Get county data as Key => Value Pair
     *
     * @return unknown
     */
    public static function getCounties(){

        $sql = Doctrine_Query::create()
        ->select('c.Id, c.Name')
        ->from('Counties c')
        ->where('c.Status = ? ', sfConfig::get('app_UserStatus_Active') )
        ->orderBy('c.Name ASC');

        $result = $sql->fetchArray();
        #clsCommon::pr($result);

        $countiesArr = array();
        foreach ($result as $value ){
            $countiesArr[$value['Id']] = $value['Name'];
        }

        #clsCommon::pr($stateArr);exit;
        $sql->free();
        return $countiesArr;
    }


}