<?php

/**
 * CustomerPaymentSentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CustomerPaymentSentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CustomerPaymentSentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CustomerPaymentSent');
    }
}