<?php

/**
 * FAQs
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    counceledge
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class FAQs extends BaseFAQs
{
  public function updateStatus($snId,$ssStatus)
  {
    if(!is_numeric($snId) || !is_string($ssStatus))
      return false;
 
      Doctrine_Query::create()
	->update('FAQs')
	->set('status', '?', $ssStatus)
	->where('id = ?', $snId)
	->execute();
  }
  
  public function getPersonalList($allIds)
	{
	   $result = Doctrine_Query::create()
					->select('f.*')
					->from('FAQs f')
					->where('f.Globle = ?',"Yes")
					->andWhere('f.status = ?',sfConfig::get('app_FAQs_Active'))
					->whereNotIn('f.id', $allIds);
					//->execute();
					
		return $result;
	}
	
	public function globalDelete($FAQId)
	{
	  if(!is_numeric($FAQId))
		return false; 

	  Doctrine_Query::create()
		  ->delete('FAQs f')
		  ->where('f.id = ?', $FAQId)
		  ->execute();

	  return true;
	}
}