<?php

/**
 * ForumTopics
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    counceledge
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ForumTopics extends BaseForumTopics
{
	public function __toString()
	{
		  return $this->getTopic();
	}
	
	public function topicListing()
	{
	  $result = Doctrine_Query::create()
					  ->select('ft.*')
					  ->from('ForumTopics ft');
					  

		  return $result;
	}

	public function viewForumsTopicQuery($snId)
	{
	  $saRecord = Doctrine_Query::create()
					  ->select('ft.*,ftf.*,ftu.*')
					  ->from('ForumTopics ft')
					  ->leftJoin('ft.ForumTopicsForums ftf')
					  ->leftJoin('ft.ForumTopicsUsers ftu')
					  ->where('ft.Id = ?',$snId)
					  ->fetchArray();

	  return $saRecord;

	}
	
	public function changeTopicStatus($snId,$ssStatus)
	{

	  if(!is_numeric($snId) || $snId == '' || $ssStatus == '')
		return false;

		Doctrine_Query::create()
		->update('ForumTopics')
		->set('Status', '?', $ssStatus)
		->where('id = ?', $snId)
		->execute();

		return true;
	}
	
	/**
     * function is for update forums reply data
     *
     * @return boolean
     */
	public function updateTopicReplyData($replyId, $lastReplyUser, $topicId, $lastReplyDateTime)
	{

		if(!is_numeric($replyId) || !is_numeric($lastReplyUser) || !is_numeric($topicId))
			return false;

		$sql = Doctrine_Query::create()
        ->update('ForumTopics FT')
        ->set('FT.LastRepliedId', $replyId)
        ->set('FT.LastRepliedBy', $lastReplyUser)
        ->set('FT.TotalReplies', ('FT.TotalReplies + 1'))
        ->set('FT.LastRepliedDateTime', "'$lastReplyDateTime'")
        ->where('FT.Id = ?', $topicId)
        ->execute();

        return true;
	}
	
	/**
     * function is for update forums reply data delete time
     *
     * @return boolean
     */
	public function DeleteTimeUpdateTopicReplyData($replyId, $lastReplyUser, $topicId, $lastReplyDateTime)
	{
		if(!is_numeric($replyId) || !is_numeric($lastReplyUser) || !is_numeric($topicId))
			return false;

		$sql = Doctrine_Query::create()
        ->update('ForumTopics FT')
        ->set('FT.LastRepliedId', $replyId)
        ->set('FT.LastRepliedBy', $lastReplyUser)
        ->set('FT.TotalReplies', ('FT.TotalReplies - 1'))
        ->set('FT.LastRepliedDateTime', "'$lastReplyDateTime'")
        ->where('FT.Id = ?', $topicId)
        ->execute();

        return true;
	}
	
	/**
     * function is for update topic view
     *
     * @return boolean
     */
	public function updateMostView($topicId)
	{
		if(!is_numeric($topicId))
			return false;

		$sql = Doctrine_Query::create()
        ->update('ForumTopics FT')
        ->set('FT.TotalViews', ('FT.TotalViews + 1'))
        ->where('FT.Id = ?', $topicId)
        ->execute();

        return true;
	}
}