<?php

/**
 * ForumCategories
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    counceledge
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ForumCategories extends BaseForumCategories
{

  public function __toString()
  {
        return $this->getTitle();
  }

  public function categoriesListing()
  {
	$result = Doctrine_Query::create()
					->select('f.*')
					->from('ForumCategories f')
					->where('f.Status != ?',"Deleted");

		return $result;
  }
  public function changeStatus($snId,$ssStatus)
  {
  
	if(!is_numeric($snId) || $snId == '')
	  return false;

	  Doctrine_Query::create()
	  ->update('ForumCategories')
	  ->set('Status', '?', $ssStatus)
	  ->where('id = ?', $snId)
	  ->execute();

	  return true;
  }
  
  public function viewForumCategoryQuery($snId)
  {
	$saRecord = Doctrine_Query::create()
					->select('fc.*')
					->from('ForumCategories fc')
					->where('fc.Id = ?',$snId)
					->fetchArray();

	return $saRecord;

  }
}