<?php

/**
 * ForumReplyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ForumReplyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ForumReplyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ForumReply');
    }

    public static function getLastReplyOfForums($forumsId, $topicId)
    {
		$sql = Doctrine_Query::create()
				->from('ForumReply FR')
				->where("FR.ForumId = ?",$forumsId)
				->andWhere('FR.TopicId = ?', $topicId)
				->andWhere("FR.Status = ?","Active")
				->orderBy("FR.Id Desc")
				->limit(1)
				->fetchArray();

		return $sql;
    }
}