<?php

/**
 * ForumCategoriesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ForumCategoriesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ForumCategoriesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ForumCategories');
    }
}