<?php

/**
 * MediaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MediaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MediaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Media');
    }

    /**
     * This function returns BannerForeground Images.
     *
     * @return array
     */
    public static function getForegroundImage($type)
    {
		$saRecord = Doctrine_Query::create()
					  ->select('m.ImageName,m.Title')
					  ->from('Media m')
					  ->where('m.Type = ?',$type)
					  ->orderBy("m.Id Desc")
					  ->fetchArray();
					  
		return $saRecord;
    }

}