<?php

/**
 * Media
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    counceledge
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Media extends BaseMedia
{
	public function mediaListing()
	{
	  $result = Doctrine_Query::create()
					  ->select('m.*')
					  ->from('Media m');
		  return $result;
	}
	
	public function mediaViewQuery($snId)
	{
		if(!is_numeric($snId))
			return false;

		 $saRecord = Doctrine_Query::create()
					  ->select('m.*')
					  ->from('Media m')
					  ->where('m.Id = ?',$snId)
					  ->fetchArray();

		return $saRecord;
	}
}
