<?php

/**
 * PermissionCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PermissionCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PermissionCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PermissionCategory');
    }

    
    public static function getAllRecordList()
    {
        $sql = Doctrine_Query::create()
            ->from('PermissionCategory pr')
            ->leftJoin('pr.PermissionCategoryPermissions pc')
            ->execute(array(),Doctrine_Core::HYDRATE_ARRAY );
        return $sql;
         /*
            $arrListReturn = array();
       
            foreach($sql as $sql):
                $arrListReturn[$sql['Name']]= $sql['Name'];
                foreach($sql['PermissionCategoryPermissions'] as $ss):
                    $arrListReturn[$ss['UniqueKey']]= $ss['UniqueKey'];
                endforeach;
            endforeach;
        
            //echo "<pre>"; print_r($arrListReturn); exit;
            return $arrListReturn;
         */
    }
    public static function getPermissionList($id)
    {       
        
        $sql = Doctrine_Query::create()
        ->from('RolesXPermission rxp')
        ->where('rxp.RoleId = ?',$id);
        $arrList = $sql->execute(array(),Doctrine_Core::HYDRATE_ARRAY);
        

        $arrPermissionList = array();
        if (count($arrList)>0) {
            foreach ($arrList as $arrPer){
                //$arrPermissionList[] = 'parentCategory_'.$arrPer['PermissionCategoryId'].'_'.$arrPer['PermissionId'];
                $arrPermissionList[] = $arrPer['PermissionId'];
            }
        }
        //clsCommon::pr($arrPermissionList,1); die;
        return $arrPermissionList;
    }
}
