<?php

/**
 * RolesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RolesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RolesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Roles');
    }
    
    /**
     * THIS FUNCTION IS USE TO CHECK THE UNIQ NAME OF ROLES
     *
     * @param unknown_type $id
     * @param unknown_type $newName
     * @return flage variable i.e. true or flase
     */
    public static function emailName($id,$newName)
    {
        $dbName = Doctrine_Query::create()
        ->select('r.Name')
        ->from('Roles r')
        ->where('r.id != ?',$id)
        ->andWhere('r.Name = ?',$newName);
        $resultName = $dbName->fetchArray();
        $dbName->free();
        if (count($resultName) == 1) {
            return true;
        }else {
            return false;
        }
    }
    
    public static function getRoleList()
    {
        $sql = Doctrine_Query::create()
        ->from('Roles r')
        ->where('r.Status = ?',sfConfig::get('app_Status_Active'))
        ->orderBy('r.Name ASC')
        ->execute(array(),Doctrine_Core::HYDRATE_ARRAY );
        $arrListReturn = array();
        for ($i = 0; $i<count($sql); $i++)
        {
            $arrListReturn[$sql[$i]['Id']] = $sql[$i]['Name'];
        }
        return $arrListReturn;
    }
    
    /**
     * THIS IS USE FOR COUNT OF ALL THE ROLES.
     *
     * @return unknown
     */
    public static function getAllRecord()
    {
        $sql = Doctrine_Query::create()
        ->from('Roles r')
        ->execute(array(),Doctrine_Core::HYDRATE_ARRAY );
        return count($sql);
    }
}