<?php

/**
 * SiteEmailsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SiteEmailsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SiteEmailsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SiteEmails');
    }
}