<?php

/**
 * ThemeBanner
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    counceledge
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ThemeBanner extends BaseThemeBanner
{
	public function changeStatus($snId,$ssStatus)
    {
        if(!is_numeric($snId) || $ssStatus == '')
			return false;

			Doctrine_Query::create()
			->update('ThemeBanner')
			->set('Status', '?', $ssStatus)
			->where('id = ?', $snId)
			->execute();

        return true;
    }
    
     /**
     * This function is for delete website data
     *
     * @param  integer $websiteId
     * @auther jaydip dodiya
     * @return boolean
     */
	public function deleteThemeBannerData($websiteId)
	{
		if(!is_numeric($websiteId))
			return false;

		Doctrine_Query::create()
		->delete('ThemeBanner T')
		->where('T.WebsiteId  = ?', $websiteId)
		->execute();

		return true;
	}
}
