<?php

/**
 * ThemeBannerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ThemeBannerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ThemeBannerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ThemeBanner');
    }

    public static function viewThemeBanner($snId)
    {
        if(!is_numeric($snId))
        return false;

        $asThemeBannerData = Doctrine_Query::create()
        ->select("tb.*,tbt.*")
        ->from('ThemeBanner tb')
        ->leftJoin("tb.ThemeBannerTheme tbt")
        ->where('tb.Id = ?', $snId)
        ->fetchArray();
        return $asThemeBannerData;
    }

    /**
     * Function to Get Website Specific Banners
     *
     * @param unknown_type $websiteId
     */
    public static function getWebsiteBanners($websiteId){

        $sql = Doctrine_Query::create()
        ->from('ThemeBanner tb')
        //->leftJoin("tb.ThemeBannerTheme tbt")
        ->where('tb.WebsiteId = ?', $websiteId)
        ->andwhere('tb.Status = ?', sfConfig::get('app_Status_Active'))
        ->orderBy('tb.Id DESC');

        $banner = $sql->fetchArray();
        #clsCommon::pr($banner);
        return $banner;

    } // End of Function

    /**
     * Function to check whether Banner for Website Exist or not
     *
     * @param unknown_type $websiteId
     */
    public static function checkBannerExist($websiteId){

        $sql = Doctrine_Query::create()
        ->from('ThemeBanner tb')
        ->where('tb.WebsiteId = ?', $websiteId)
        ->andwhere('tb.Status = ?', sfConfig::get('app_Status_Active'));
        $bannerCount = $sql->count();
        if($bannerCount > 0)
            return true;
        else
            return false;
    } // End of Function
}