<?php

/**
 * Theme
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    counceledge
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Theme extends BaseTheme
{
	/*this function is for limitwords	 */
	public function __toString()
	{
			return $this->getName();
	}

    public function limitWords($text, $limit)     
    {
        $text = strip_tags($text);
        $words = str_word_count($text, 2);
        $pos = array_keys($words);
        if (count($words) > $limit) {
            $text = substr($text, 0, $pos[$limit]) . ' ...';
        }
        return $text;
    }

    public function changeStatus($snId , $ssStatus)
    {
        if(!is_numeric($snId) || !is_string($ssStatus))
		return false;

		$ssQuery =Doctrine_Query::create()
				->update('Theme')
				->set('status', '?', $ssStatus)
				->where('id = ?', $snId)
				->execute();
    }
    
    public function getDefaultId()
    {
		$asResult = Doctrine_Query::create()
						->select("t.id")
						->from("Theme t")
						->where("t.IsDefault = ?","Yes")
						->fetchArray();

		return $asResult;
    }
    
    public function updateTableValue($tableKey,$value,$snId)
    {
		Doctrine_Query::create()
				->update('Theme')
				->set($tableKey, '?', $value)
				->where('id = ?', $snId)
				->execute();
		return true;
    }
}
