<?php

/**
 * ThemeOptions
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    counceledge
 * @subpackage model
 * @author     Krunal Nerikar
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ThemeOptions extends BaseThemeOptions
{
	public function __toString()
	{
		return $this->getOptionKey();
	}

	/**
     * This function is for delete website data
     *
     * @param  integer $websiteId
     * @auther jaydip dodiya
     * @return boolean
     */
	public function deleteThemeOptionsWebsiteData($websiteId)
	{
		if(!is_numeric($websiteId))
			return false;

		Doctrine_Query::create()
		->delete('ThemeOptions T')
		->where('T.WebsiteId = ?', $websiteId)
		->execute();

		return true;
	}
}