<?php

/**
 * ThirdPartyPaymentReceivedTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ThirdPartyPaymentReceivedTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ThirdPartyPaymentReceivedTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ThirdPartyPaymentReceived');
    }
}