<?php

/**
 * ThirdPartiesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ThirdPartiesTable extends Doctrine_Table
{

    /**
     * Returns an instance of this class.
     *
     * @return object ThirdPartiesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ThirdParties');
    }

    public function getName(){
        return $this->getName();
    }

    /**
     * This function returns Active 3rd Parties .
     *
     * @return unknown
     */
    public static function getThirdParties()
    {
        $queryUser = Doctrine_Query::create()
        ->select('tp.Id, tp.Name')
        ->from(' ThirdParties tp')
        ->where('tp.Status = ?', sfConfig::get('app_UserStatus_Active'))
        ->orderBy('tp.Name ASC')  ;

        $result = $queryUser->fetchArray();
        $queryUser->free();
        $tpArr = array();

        if(!empty($result)) {
            for($i=0; $i<count($result); $i++) {
                $tpArr[$result[$i]['Id']]  = $result[$i]['Name'];
            }
        }

        return $tpArr;

    } // End of Function


}