<?php

/**
 * UserProfileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserProfileTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserProfileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserProfile');
    }
    
    /**
     * this function is use for checking the url exist or not in db
     *
     * @param unknown_type $url
     * @return unknown
     */
    public static function urlExist($url){
        $dbUrl = Doctrine_Query::create()
        ->from('UsersWebsite up')
        ->where('up.WebsiteURL = ?',$url);
        $resultUrl = $dbUrl->fetchArray();
        $dbUrl->free();
        //echo count($resultUrl);die;
        if (count($resultUrl) == 1) {
            return true;
        }else {
            return false;
        }
    }
}