<?php

/**
 * UserPracticeAreaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserPracticeAreaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserPracticeAreaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserPracticeArea');
    }
    public static function getRecordList($id)
    {
        $sql = Doctrine_Query::create()
        ->select('upa.PracticeareaId,upa.Level')
        ->from('UserPracticeArea upa')
        ->where('upa.UserId = ?',$id);
        $arrList = $sql->execute(array(),Doctrine_Core::HYDRATE_ARRAY);
        #clsCommon::pr($arrList,1);
        $arrPracticeArea = array();
        if(count($arrList) > 0 ){
            foreach ($arrList as $arrPA){
                #if ($arrPA['PracticeareaId'] == 1) {
                if ($arrPA['PracticeareaId'] == -1) {
                    $arrPracticeArea[] = -1;
                }else {
                    #$arrPracticeArea[] = $arrPA['PracticeareaId'];
                    $arrPracticeArea[] = $arrPA['PracticeareaId'].'-'.$arrPA['Level'];
                }
            }
        }
        #clsCommon::pr($arrPracticeArea);
        return implode(",", $arrPracticeArea);

    }

    public static function deleteOldPracticeAreaData($id){
        $del = Doctrine_Query::create()
        ->delete()
        ->from('UserPracticeArea upa')
        ->where('upa.UserId = ?',$id)
        ->execute();
    }

    public static function getSearchData($data){


    }

    public static function getParentId($id){
        $sql = Doctrine_Query::create()
        ->from('PracticeAreas upa')
        ->where('upa.Id = ?',$id);
        $reult = $sql->fetchOne();

        $reult->getParentId();
        return $reult->getParentId();

    }

    /**
     * Function to get User Practice Area Level Wise 
     *
     */

    public static function getFeaturedCustomerPracticeArea($id) {
        echo sfConfig::get('app_CaseStatus_Active');
        $sql = Doctrine_Query::create()
        //->select('upa.PracticeareaId,upa.Level')
        ->from('UserPracticeArea upa')
        ->leftJoin('upa.UserPracticeAreaPracticeAreas pa')
        ->where('upa.UserId = ?', $id)
        ->andWhere('pa.Id != ? ', '-1')
        ->andWhere('pa.Status = ? ', 'Active')
        ->orderBy('upa.Level ASC, pa.Name ASC')
        ->limit(2);

        $arrList = $sql->fetchArray();
        #clsCommon::pr($arrList);
        #die;
        return $arrList;


    } // End of Function

}