<?php

/**
 * WebsitePracticeAreaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WebsitePracticeAreaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WebsitePracticeAreaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WebsitePracticeArea');
    }

    /**
	 * THIS FUNCTION IS USED FOR EXISTING SLUG VALUE
	 *
	 * @param unknown_type $websiteId
	 * @param unknown_type $title
	 * @return OBJECT
	 */
    public static function checkSlugExist($websiteId,$title, $act, $id = NULL)
    {
        $sql = Doctrine_Query::create()
        ->from('WebsitePracticeArea w')
        ->where('w.WebsiteId = ?',$websiteId)
        ->andWhere('w.Slug = ?',$title);
        //echo $title;
        //echo $sql->getSqlQuery();die;
        if($act == 'edit' && !empty($id ))
        $sql->andWhere('w.Id != ?', $id);

        return $sql->fetchArray();
    }

    /**
     * Function to get Website Practice Area
     *
     * @param unknown_type $websiteId
     */
    public static function getPracticeArea($websiteId, $limit = 17)
    {
        $sql = Doctrine_Query::create()
        ->select('w.Id, w.Title, w.Slug')
        ->from('WebsitePracticeArea w')
        ->where('w.WebsiteId = ?', $websiteId)
        ->andWhere('w.Status = ?', sfConfig::get('app_Status_Active'))
        ->orderBy('w.Title ASC')
        ->limit($limit);
        #echo $sql->getSqlQuery();
        #clsCommon::pr($sql->fetchArray());
        return $sql->fetchArray();
    } // End of Function


    /** Function to Get Practice Area Id based on Slug For  Theme Default content Setup
     * 
     * 
     * @param unknown_type $websitId
     * @param unknown_type $SlugTitle
     * @return unknown
     */
    public static function getPracticeAreaBasedonSlug($websitId, $SlugTitle){
        $sql = Doctrine_Query::create()
        ->from('WebsitePracticeArea w')
        ->where('w.WebsiteId = ?', $websitId)
        ->andWhere('w.Slug = ?', $SlugTitle);
        $result = $sql->fetchArray();
        #clsCommon::pr($returnHome, 1);
        $sql->free();
        return $result[0]['Id'];

    } // End of Function


}