<?php

/**
 * WebsiteXFAQsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WebsiteXFAQsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WebsiteXFAQsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WebsiteXFAQs');
    }

    /**
     * This function is for counceledge Listing
     *
     * @param  integer $webId
     * @return string boolean
     */
    public function counceledgeLegaltripListing($webId)
    {
        if(!is_numeric($webId))
        return false;

        $qSearch = Doctrine_Query::create()
        ->select('wxf.*,fa.*')
        ->from('WebsiteXFAQs wxf')
        ->leftJoin('wxf.WebsiteXFAQsFAQs fa')
        ->where('fa.status = ?',sfConfig::get('app_FAQs_Active'))
        ->andWhere('wxf.WebsiteId = ?',$webId)
        ->orderBy("wxf.Ordering");

        return $qSearch;
    }

    /**
     * THIS FUNCTION IS USE FOR FETCH THE DATA FOR COUCELEDGE WEBSITE
     *
     * @return OBJECT OF COUNCELEDGE
     */
    public static function getFaqsQuestionAnswerForView()
    {
        $sql = Doctrine_Query::create()
        ->from('WebsiteXFAQs wxf')
        ->where('wxf.WebsiteId = ?',1)
        ->andWhere('wxf.Status = ?',sfConfig::get('app_Status_Active'))
        ->orderBy('wxf.Ordering ASC');
        return $objFaqs = $sql->execute();
    }

    /**
     * This function will retunr Max Odering of Question 
     *
     * @param unknown_type $WebsiteId
     * @return unknown
     */
    public static function faqMaxOrder($WebsiteId)
    {
        if(!is_numeric($WebsiteId))
        return false;

        $maxOrder =	Doctrine_Query::create()
        ->select("MAX(w.Ordering) as max")
        ->from('WebsiteXFAQs w')
        ->where('w.WebsiteId = ?', $WebsiteId)
        ->fetchArray();

        if(empty($maxOrder[0]["max"]) &&  $maxOrder[0]["max"] == '') {
            return 0;
        }else {
            return ( ($maxOrder[0]["max"] + 1) );
        }
    } // End of Function

    /**
     * This function is for legalgrip Listing
     *
     * @param  integer $webId
     * @return string boolean
     */
    public static function legalgripListing($webId)
    {
        if(!is_numeric($webId))
			return false;

        $qSearch = Doctrine_Query::create()
        ->select('wxf.*,fa.*')
        ->from('WebsiteXFAQs wxf')
        ->leftJoin('wxf.WebsiteXFAQsFAQs fa')
        ->where('fa.status = ?',sfConfig::get('app_UserStatus_Active'))
        ->where('wxf.status = ?',sfConfig::get('app_UserStatus_Active'))
        ->andWhere('wxf.WebsiteId = ?',$webId)
        ->orderBy("wxf.Ordering");

        return $qSearch;
    }

}