# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
#all:

dev:
      site_url:                      'http://counceledge.demo.brainvire.com'
      smtp_username:                 'crazydev82@gmail.com'
      smtp_password:                 'mitul123'
      smtp_host:                     'smtp.gmail.com'
      smtp_port:                     '465'
      smtp_security:                 'ssl'
      smtp_flag:                     'On'    
stage:
      site_url:                      'http://counceledge.demo.brainvire.com'
      smtp_username:                 'crazydev82@gmail.com'
      smtp_password:                 'mitul123'
      smtp_host:                     'smtp.gmail.com'
      smtp_port:                     '465'
      smtp_security:                 'ssl'
      smtp_flag:                     'On'    
prod:
      site_url:                      'http://vcdev.demo.brainvire.com'
      smtp_username:                 'crazydev82@gmail.com'
      smtp_password:                 'mitul123'
      smtp_host:                     'smtp.gmail.com'
      smtp_port:                     '465'
      smtp_security:                 'ssl'
      smtp_flag:                     'On'
    
all:
  mediapath: "Media/"
  no_of_records_per_page: 10
  max_end_range: 200000
  .pwdEncDecKey:
    pwdEncDecKey:               '1HJ3AL6EC7MP9TS7O5' 	

  .caseFileType:
    caseFileType:
      0:   application/pdf 
      1:   application/msword
      2:   application/vnd.openxmlformats-officedocument.wordprocessingml.document
      3:   application/vnd.ms-excel
      4:   application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
    caseInvoicePath: "caseBills/"
      
  UserStatus:
    Active:                       Active
    Deleted:                      Deleted
    Inactive:                     Inactive
    Pending:                      Pending 

  UserType:
    Admin:                        Admin
    Staff:                        Staff
    Customer:                     Customer
    User:                         User

  FAQs:
    Inactive:                    Inactive
    Active:                      Active

  CaseStage:
    Submitted:                    Submitted
    Accepted:                     Accepted
    Paid:                         Paid
    3rdPartyBillsSubmitted:       3rdPartyBillsSubmitted
    Close:                        Close
    
  CaseStatus:
    Active:                       Active
    Deleted:                      Deleted
    Inactive:                     Inactive

  CaseActivityType:
    CustomerBillsSubmitted:       CustomerBillsSubmitted
    3rdPartyBillsSubmitted:       3rdPartyBillsSubmitted
    CheckSent:                    CheckSent 
    PaymentReceived:              PaymentReceived   
        
  Status:
    Active:                      Active
    Inactive:                    Inactive
    Deleted:                     Deleted

  .imageType:
    imageType:
      0:   image/jpeg 
      1:   image/jpg
      2:   image/png
      3:   image/gif
    profileImagePath: "Theme/"

  ImageSize:
    Height:  200
    Width:   200
  ThumbnailPath: 
    Thumbpath:  '/uploads/Theme/thumb/'
