<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/01/23 14:24:54

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=counceledge',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
