# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Legal Grip
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [main.css, legalgrip/style.css, legalgrip/jquery.selectbox.css]

  javascripts:    [admin/AdminCommon.js, legalgrip/jquery-1.7.1.min.js, legalgrip/jquery.validate.js, legalgrip/jquery.selectbox-0.2.js, legalgrip/jquery.placeholder.js]

  has_layout:     true
  layout:         layout
